language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"

branches:
  only:
    - master

install:
  - pip install .[tf,gym,retro]

script:
  - pytest

notifications:
  email:
    recipients:
      - tensorforce.team@gmail.com
    on_success: never
    on_failure: always
